plugins {
    id "org.hidetake.ssh" version "2.11.2"
}

remotes {
    orangepi {
        host = findProperty("devAddr") ?: "10.1.72.14"
        port = (findProperty("devPort") ?: 22) as int
        user = "pi"
        password = "raspberry"
    }
}

task viewBuild {
    group = "Vision Deployment"
    description = "builds + starts docker container (requires internet access)"
    doLast {
        println "this build requires both your computer and pi to be connected to internet!"
        ssh.run {
            session(remotes.orangepi) {
                def dirName = project.projectDir.getName()
                put from: project.projectDir, into: "/home/pi"
                println "running docker build (will disconnected from static)"
                executeScript """
                    sudo nmcli conn down static-end1 && sleep 5
                    cd ~/viewer
                    sudo docker build . -t viewer --network=host
                    sudo docker run \
                        --name=viewer-sys \
                        --restart=always \
                        --network=host \
                        --device /dev/bus/usb \
                        -v .:/run/viewer/:ro \
                        viewer
                    sudo nmcli conn up static-end1""", pty: true
            }
        }
    }
}

task viewDeploy {
    group = "Vision Deployment"
    description = "deploy viewer system code (only for non-docker code)"
    doLast {
        ssh.run {
            session(remotes.orangepi) {
                def dirName = project.projectDir.getName()
                put from: project.projectDir, into: "/home/pi"
                println "vision code uploaded to ~/$dirName, reloading docker."
                executeScript "cd ~/viewer && sudo docker restart viewer-sys"
            }
        }
    }
}